stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven
      shellScript: mvn clean package install
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: order/springboot1
      pushRemote: true
      registry: www.j116.cn
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
